version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: web-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webapp
      MYSQL_USER: webuser
      MYSQL_PASSWORD: webpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - web-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/webapp
      SPRING_DATASOURCE_USERNAME: webuser
      SPRING_DATASOURCE_PASSWORD: webpassword
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - web-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web-frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    depends_on:
      - backend
    networks:
      - web-network

volumes:
  mysql_data:

networks:
  web-network:
    driver: bridge