spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/webapp}
    username: ${SPRING_DATASOURCE_USERNAME:webuser}
    password: ${SPRING_DATASOURCE_PASSWORD:webpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

# CORS configuration
cors:
  allowed-origins: "http://localhost:3000"